services:
  idrive:
    build: ./idrive/build/
    image: snorre0815/idrive-docker:latest
    container_name: idrive
    volumes:
      - /path/to/config/cache:/opt/IDriveForLinux/idriveIt/cache
      - /path/to/config/user_profile:/opt/IDriveForLinux/idriveIt/user_profile
      - /path/to/config/idrivecrontab.json:/opt/IDriveForLinux/idriveIt/idrivecrontab.json
      - /path/to/backup:/source/1:ro
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC

